#!/usr/bin/env node

/**
 * sync-tools.mjs — Auto-sync gateway endpoints to MCP tools
 *
 * Run before build: node scripts/sync-tools.mjs
 *
 * 1. Fetches all endpoints from gateway.spraay.app
 * 2. Scans src/index.ts for already-registered tool paths
 * 3. Generates tool definitions for any missing endpoints
 * 4. Writes them to src/auto-tools.ts
 * 5. src/index.ts imports and calls registerAutoTools()
 *
 * This means hand-crafted tools stay in index.ts untouched,
 * and new gateway endpoints get auto-generated tools.
 */

const GATEWAY_URL = process.env.SPRAAY_GATEWAY_URL || "https://gateway.spraay.app";

async function main() {
  // 1. Fetch gateway info
  console.log("🔄 Fetching gateway endpoints...");
  const res = await fetch(`${GATEWAY_URL}/`);
  const info = await res.json();
  console.log(`✅ Gateway v${info.version} — ${info.totalEndpoints} endpoints`);

  // 1b. Fetch the OpenAPI doc for typed per-endpoint input schemas (best-effort).
  //     If this fails or an endpoint isn't documented, we fall back to generic params/body.
  let openapiFields = new Map(); // "METHOD /path" -> { query:[...], body:[...] }
  try {
    const oaRes = await fetch(`${GATEWAY_URL}/openapi.json`);
    if (oaRes.ok) {
      openapiFields = buildOpenApiFieldMap(await oaRes.json());
      console.log(`🧩 OpenAPI: typed input schemas for ${openapiFields.size} operations`);
    } else {
      console.log("⚠️  OpenAPI fetch returned non-OK; using generic params/body schemas.");
    }
  } catch {
    console.log("⚠️  OpenAPI fetch failed; using generic params/body schemas.");
  }

  // 2. Collect all endpoint paths from gateway
  const SKIP = new Set(["/", "/health", "/stats", "/.well-known/x402.json"]);
  const allEndpoints = [];

  for (const [key, value] of Object.entries(info.endpoints.free)) {
    const match = key.match(/^(GET|POST|PUT|PATCH|DELETE)\s+(.+)$/);
    if (!match) continue;
    const path = match[2];
    if (SKIP.has(path)) continue;
    allEndpoints.push({ method: match[1], path, value, isFree: true });
  }
  for (const [key, value] of Object.entries(info.endpoints.paid)) {
    const match = key.match(/^(GET|POST|PUT|PATCH|DELETE)\s+(.+)$/);
    if (!match) continue;
    const path = match[2];
    if (SKIP.has(path)) continue;
    allEndpoints.push({ method: match[1], path, value, isFree: false });
  }

  // 3. Read existing index.ts and find which paths are already covered
  const fs = await import("fs");
  const indexSrc = fs.readFileSync("src/index.ts", "utf-8");

  // Normalize any path parameter — template literal (${jobId}) OR colon form (:jobId) —
  // to a single placeholder, so coverage matching is param-NAME-agnostic. Prevents
  // generating a duplicate auto-tool for an endpoint a manual tool already covers under a
  // differently-named param (e.g. manual ${jobId} vs gateway :jobId). Literal path
  // segments (e.g. /list) are untouched, so genuinely distinct endpoints stay distinct.
  const normalizePath = (p) => p.replace(/\$\{[^}]+\}/g, ":param").replace(/:\w+/g, ":param");

  // Match paths in api.get("/api/v1/...") and api.post("/api/v1/...") calls
  const coveredPaths = new Set();
  const pathRegex = /api\.(get|post|patch|put|delete)\(["'`]([^"'`]+)["'`]/gi;
  let m;
  while ((m = pathRegex.exec(indexSrc)) !== null) {
    coveredPaths.add(normalizePath(m[2]));
  }

  // Also check for api({ method: "PATCH", url: "..." }) pattern
  const patchRegex = /url:\s*["'`]([^"'`]+)["'`]/gi;
  while ((m = patchRegex.exec(indexSrc)) !== null) {
    coveredPaths.add(normalizePath(m[1]));
  }

  console.log(`📋 ${coveredPaths.size} paths already in index.ts`);

  // 4. Find missing endpoints
  const missing = allEndpoints.filter(ep => !coveredPaths.has(normalizePath(ep.path)));
  console.log(`🆕 ${missing.length} new endpoints to generate`);

  if (missing.length === 0) {
    console.log("✅ All endpoints covered! Nothing to generate.");
    // Write empty auto-tools file
    fs.writeFileSync("src/auto-tools.ts", `// Auto-generated — all endpoints already covered in index.ts\nimport { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";\nexport function registerAutoTools(_server: McpServer, _api: any) {}\nexport const autoToolCount = 0;\n`);
    return;
  }

  // 5. Generate tool code
  let code = `// ⚡ AUTO-GENERATED by scripts/sync-tools.mjs — DO NOT EDIT\n`;
  code += `// Run "node scripts/sync-tools.mjs" to regenerate\n`;
  code += `// Generated: ${new Date().toISOString()}\n\n`;
  code += `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";\n`;
  code += `import { z } from "zod";\n\n`;
  code += `const ethAddr = z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Must be a valid Ethereum address");\n`;
  code += `const positiveAmount = z.string().regex(/^\\d+(\\.\\d+)?$/, "Must be a positive number");\n\n`;
  code += `export const autoToolCount = ${missing.length};\n\n`;
  code += `export function registerAutoTools(server: McpServer, api: any) {\n`;

  for (const ep of missing) {
    const toolName = deriveToolName(ep.path);
    const category = deriveCategory(ep.path);
    let price = "FREE";
    let description = ep.value;

    if (!ep.isFree) {
      const pm = ep.value.match(/^\$([0-9.]+)\s*-\s*(.+)$/);
      if (pm) {
        price = `$${pm[1]} USDC`;
        description = pm[2].trim();
      } else if (ep.value.startsWith("FREE")) {
        price = "FREE";
        description = ep.value.replace(/^FREE\s*-?\s*/, "").trim() || ep.value;
      }
    }

    const isRead = ep.method === "GET";
    const annotations = isRead
      ? "{ readOnlyHint: true, openWorldHint: true }"
      : "{ readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true }";

    // Capture ANY path parameter (e.g. :id, :jobId). Its value is interpolated into the
    // URL; the MCP arg uses the raw gateway param name so the handler can forward cleanly.
    const pathParamMatch = ep.path.match(/:(\w+)/);
    const pathParam = pathParamMatch ? pathParamMatch[1] : null;
    const hasPathParam = !!pathParam;
    const urlExpr = hasPathParam
      ? "`" + ep.path.replace(`:${pathParam}`, "${args." + pathParam + "}") + "`"
      : `"${ep.path}"`;

    // Typed input fields from the OpenAPI doc for this exact operation, if documented.
    const oaEntry = openapiFields.get(`${ep.method} ${ep.path}`);
    let typedQuery = oaEntry && oaEntry.query.length ? oaEntry.query : null;
    let typedBody  = oaEntry && oaEntry.body.length  ? oaEntry.body  : null;
    // Dedupe: if a path param shares a name with an OpenAPI field (e.g. :id plus an "id"
    // parameter), the path-param field wins — drop the duplicate so the generated Zod
    // object literal never declares the same key twice.
    if (hasPathParam) {
      if (typedQuery) { typedQuery = typedQuery.filter(f => f.name !== pathParam); if (!typedQuery.length) typedQuery = null; }
      if (typedBody)  { typedBody  = typedBody.filter(f => f.name !== pathParam);  if (!typedBody.length)  typedBody  = null; }
    }

    // Assemble the Zod input shape + the handler body + a usage hint for the description.
    const fieldParts = [];
    if (hasPathParam) {
      fieldParts.push(`${JSON.stringify(pathParam)}: z.string().min(1).describe("Path parameter that identifies the resource")`);
    }
    let schemaStr, handlerBody, usageHint;

    if (isRead) {
      if (typedQuery) {
        fieldParts.push(zFieldsFromList(typedQuery));
        schemaStr = `{ ${fieldParts.join(", ")} }`;
        if (hasPathParam) {
          handlerBody = `const query = { ...args }; delete query.${pathParam};\n        const res = await api.get(${urlExpr}, { params: query });`;
        } else {
          handlerBody = `const res = await api.get(${urlExpr}, { params: args });`;
        }
        usageHint = "Read-only. Pass the listed fields directly as typed arguments.";
      } else if (hasPathParam) {
        schemaStr = `{ ${fieldParts.join(", ")} }`;
        handlerBody = `const res = await api.get(${urlExpr});`;
        usageHint = "Read-only. Provide the path parameter to fetch a single record.";
      } else {
        schemaStr = `{ params: z.string().optional().describe("Query parameters as JSON (e.g. {\\"key\\":\\"value\\"})") }`;
        handlerBody = `let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("${ep.path}", { params: queryParams });`;
        usageHint = "Read-only. Pass any query parameters as a JSON string via the params argument.";
      }
    } else {
      const sendBody = ep.method === "PATCH"
        ? `await api({ method: "PATCH", url: ${urlExpr}, data: body })`
        : ep.method === "PUT"
          ? `await api({ method: "PUT", url: ${urlExpr}, data: body })`
          : `await api.post(${urlExpr}, body)`;
      if (typedBody) {
        fieldParts.push(zFieldsFromList(typedBody));
        schemaStr = `{ ${fieldParts.join(", ")} }`;
        if (hasPathParam) {
          handlerBody = `const body = { ...args }; delete body.${pathParam};\n        const res = ${sendBody};`;
        } else {
          handlerBody = `const body = args;\n        const res = ${sendBody};`;
        }
        usageHint = "Provide the listed fields as typed arguments.";
      } else if (hasPathParam) {
        schemaStr = `{ ${fieldParts.join(", ")}, body: z.string().optional().describe("JSON request body") }`;
        handlerBody = `let body = {};
        if (args.body) { try { body = JSON.parse(args.body); } catch { body = { body: args.body }; } }
        const res = ${sendBody};`;
        usageHint = "Provide the path parameter; pass any additional fields as a JSON string via the body argument.";
      } else {
        schemaStr = `{ body: z.string().describe("JSON request body") }`;
        handlerBody = `let body = {};
        if (args.body) { try { body = JSON.parse(args.body); } catch { body = { body: args.body }; } }
        const res = ${sendBody};`;
        usageHint = "Pass the request payload as a JSON string via the body argument.";
      }
    }

    const desc = buildToolDescription(description, category, price, ep.isFree, usageHint);

    code += `
  server.tool(
    "${toolName}",
    "${desc.replace(/"/g, '\\"')}",
    ${schemaStr},
    ${annotations},
    async (args: any) => {
      try {
        ${handlerBody}
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: \`${toolName} error: \${error.message}\` }] };
      }
    }
  );
`;
  }

  code += `}\n`;

  fs.writeFileSync("src/auto-tools.ts", code);
  console.log(`✅ Generated src/auto-tools.ts with ${missing.length} tools`);
  console.log(`📝 Total tools: ${coveredPaths.size} (manual) + ${missing.length} (auto) = ${coveredPaths.size + missing.length}`);
}

// Build a clean, agent-friendly tool description: purpose + cost + usage hint.
// Uses only data already available to the generator (no fabricated capabilities).
function buildToolDescription(rawDesc, category, price, isFree, usageHint) {
  let base = (rawDesc || "").trim();
  if (base && !/[.!?]$/.test(base)) base += ".";
  if (base.replace(/[.!?]+$/, "").length < 4) {
    // Gateway gave little or nothing — fall back to a category-based purpose.
    base = `${category} endpoint on the Spraay x402 Gateway.`;
  }
  const cost = isFree ? "Free to call." : `Costs ${price} per call.`;
  return [base, cost, usageHint].filter(Boolean).join(" ");
}

// Parse an OpenAPI 3.x doc into a map: "METHOD /path" -> { query:[...], body:[...] }.
// query  = list of { name, type, required, description } from `parameters` (in: query)
// body   = list of { name, type, required, description } from requestBody JSON properties
function buildOpenApiFieldMap(oa) {
  const map = new Map();
  const paths = (oa && oa.paths) || {};
  for (const [routePath, methods] of Object.entries(paths)) {
    for (const [method, op] of Object.entries(methods || {})) {
      if (!op || typeof op !== "object") continue;
      const entry = { query: [], body: [] };
      if (Array.isArray(op.parameters)) {
        for (const prm of op.parameters) {
          if (prm && prm.in === "query") {
            entry.query.push({
              name: prm.name,
              type: (prm.schema && prm.schema.type) || "string",
              required: !!prm.required,
              description: prm.description || "",
            });
          }
        }
      }
      const schema = op.requestBody && op.requestBody.content
        && op.requestBody.content["application/json"]
        && op.requestBody.content["application/json"].schema;
      if (schema && schema.properties) {
        const req = Array.isArray(schema.required) ? schema.required : [];
        for (const [name, prop] of Object.entries(schema.properties)) {
          entry.body.push({
            name,
            type: (prop && prop.type) || "any",
            required: req.includes(name),
            description: (prop && prop.description) || "",
          });
        }
      }
      map.set(`${method.toUpperCase()} ${routePath}`, entry);
    }
  }
  return map;
}

// JSON-schema type -> Zod constructor (as source text).
function jsonTypeToZod(type) {
  switch (type) {
    case "string":  return "z.string()";
    case "number":  return "z.number()";
    case "integer": return "z.number().int()";
    case "boolean": return "z.boolean()";
    case "array":   return "z.array(z.any())";
    case "object":  return "z.record(z.any())";
    default:        return "z.any()";
  }
}

// Render a list of typed fields into a Zod raw-shape fragment (no surrounding braces).
function zFieldsFromList(fields) {
  return fields.map(f => {
    let zod = jsonTypeToZod(f.type);
    if (!f.required) zod += ".optional()";
    const d = (f.description || `${f.name} parameter`).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `${JSON.stringify(f.name)}: ${zod}.describe("${d}")`;
  }).join(", ");
}

function deriveToolName(path) {
  let cleaned = path
    .replace(/^\/api\/v1\//, "")
    .replace(/^\/bittensor\/v1\//, "bittensor_")
    .replace(/^\//, "")
    .replace(/:(\w+)/g, "by_$1")
    .replace(/[\/\-]/g, "_");
  // Enforce snake_case: split camelCase humps (e.g. by_jobId -> by_job_id) and lowercase.
  // Matches the runtime normalization in index.ts so generated names == served names.
  cleaned = cleaned.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
  return `spraay_${cleaned}`.replace(/__+/g, "_").replace(/_$/, "");
}

function deriveCategory(path) {
  const seg = path.replace(/^\/api\/v1\//, "").replace(/^\/bittensor\/v1\//, "bittensor/").split("/")[0];
  const map = {
    chat: "AI", models: "AI", batch: "Payments", swap: "DeFi",
    oracle: "Oracle", bridge: "Bridge", payroll: "Payroll",
    invoice: "Invoicing", analytics: "Analytics", escrow: "Escrow",
    inference: "AI Inference", notify: "Communication",
    webhook: "Webhooks", xmtp: "XMTP", rpc: "RPC",
    storage: "Storage", cron: "Scheduling", logs: "Logging",
    kyc: "KYC", auth: "Auth", audit: "Audit", tax: "Tax",
    gpu: "GPU/Compute", search: "Search/RAG",
    robots: "RTP (Robotics)", "agent-wallet": "Agent Wallets",
    prices: "DeFi", balances: "Data", resolve: "Identity",
    sctp: "Supply Chain", bittensor: "Bittensor", tokens: "Discovery",
  };
  return map[seg] || "General";
}

main().catch(err => { console.error("❌", err); process.exit(1); });
