#!/usr/bin/env node

/**
 * sync-tools.mjs — Auto-sync gateway endpoints to MCP tools
 *
 * Run before build: node scripts/sync-tools.mjs
 *
 * 1. Fetches all endpoints from gateway.spraay.app
 * 2. Scans src/index.ts for already-registered tool paths
 * 3. Generates tool definitions for any missing endpoints
 * 4. Writes them to src/auto-tools.ts
 * 5. src/index.ts imports and calls registerAutoTools()
 *
 * This means hand-crafted tools stay in index.ts untouched,
 * and new gateway endpoints get auto-generated tools.
 */

const GATEWAY_URL = process.env.SPRAAY_GATEWAY_URL || "https://gateway.spraay.app";

async function main() {
  // 1. Fetch gateway info
  console.log("🔄 Fetching gateway endpoints...");
  const res = await fetch(`${GATEWAY_URL}/`);
  const info = await res.json();
  console.log(`✅ Gateway v${info.version} — ${info.totalEndpoints} endpoints`);

  // 2. Collect all endpoint paths from gateway
  const SKIP = new Set(["/", "/health", "/stats", "/.well-known/x402.json"]);
  const allEndpoints = [];

  for (const [key, value] of Object.entries(info.endpoints.free)) {
    const match = key.match(/^(GET|POST|PUT|PATCH|DELETE)\s+(.+)$/);
    if (!match) continue;
    const path = match[2];
    if (SKIP.has(path)) continue;
    allEndpoints.push({ method: match[1], path, value, isFree: true });
  }
  for (const [key, value] of Object.entries(info.endpoints.paid)) {
    const match = key.match(/^(GET|POST|PUT|PATCH|DELETE)\s+(.+)$/);
    if (!match) continue;
    const path = match[2];
    if (SKIP.has(path)) continue;
    allEndpoints.push({ method: match[1], path, value, isFree: false });
  }

  // 3. Read existing index.ts and find which paths are already covered
  const fs = await import("fs");
  const indexSrc = fs.readFileSync("src/index.ts", "utf-8");

  // Match paths in api.get("/api/v1/...") and api.post("/api/v1/...") calls
  const coveredPaths = new Set();
  const pathRegex = /api\.(get|post|patch|put|delete)\(["'`]([^"'`]+)["'`]/gi;
  let m;
  while ((m = pathRegex.exec(indexSrc)) !== null) {
    let p = m[2];
    // Normalize template literal paths like `/api/v1/invoice/${id}`
    p = p.replace(/\$\{[^}]+\}/g, ":id");
    coveredPaths.add(p);
  }

  // Also check for api({ method: "PATCH", url: "..." }) pattern
  const patchRegex = /url:\s*["'`]([^"'`]+)["'`]/gi;
  while ((m = patchRegex.exec(indexSrc)) !== null) {
    coveredPaths.add(m[1]);
  }

  console.log(`📋 ${coveredPaths.size} paths already in index.ts`);

  // 4. Find missing endpoints
  const missing = allEndpoints.filter(ep => !coveredPaths.has(ep.path));
  console.log(`🆕 ${missing.length} new endpoints to generate`);

  if (missing.length === 0) {
    console.log("✅ All endpoints covered! Nothing to generate.");
    // Write empty auto-tools file
    fs.writeFileSync("src/auto-tools.ts", `// Auto-generated — all endpoints already covered in index.ts\nimport { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";\nexport function registerAutoTools(_server: McpServer, _api: any) {}\nexport const autoToolCount = 0;\n`);
    return;
  }

  // 5. Generate tool code
  let code = `// ⚡ AUTO-GENERATED by scripts/sync-tools.mjs — DO NOT EDIT\n`;
  code += `// Run "node scripts/sync-tools.mjs" to regenerate\n`;
  code += `// Generated: ${new Date().toISOString()}\n\n`;
  code += `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";\n`;
  code += `import { z } from "zod";\n\n`;
  code += `const ethAddr = z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Must be a valid Ethereum address");\n`;
  code += `const positiveAmount = z.string().regex(/^\\d+(\\.\\d+)?$/, "Must be a positive number");\n\n`;
  code += `export const autoToolCount = ${missing.length};\n\n`;
  code += `export function registerAutoTools(server: McpServer, api: any) {\n`;

  for (const ep of missing) {
    const toolName = deriveToolName(ep.path);
    const category = deriveCategory(ep.path);
    let price = "FREE";
    let description = ep.value;

    if (!ep.isFree) {
      const pm = ep.value.match(/^\$([0-9.]+)\s*-\s*(.+)$/);
      if (pm) {
        price = `$${pm[1]} USDC`;
        description = pm[2].trim();
      } else if (ep.value.startsWith("FREE")) {
        price = "FREE";
        description = ep.value.replace(/^FREE\s*-?\s*/, "").trim() || ep.value;
      }
    }

    const isRead = ep.method === "GET";
    const annotations = isRead
      ? "{ readOnlyHint: true, openWorldHint: true }"
      : "{ readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true }";

    const desc = `${description} | [${category}] | ${price}`;
    const hasIdParam = ep.path.includes(":id");

    // Build schema
    let schemaStr;
    if (hasIdParam && isRead) {
      schemaStr = `{ id: z.string().min(1).describe("Resource ID") }`;
    } else if (isRead) {
      schemaStr = `{ params: z.string().optional().describe("Query parameters as JSON (e.g. {\\"key\\":\\"value\\"})") }`;
    } else {
      schemaStr = `{ body: z.string().describe("JSON request body") }`;
    }

    // Build handler
    let handlerBody;
    if (isRead && hasIdParam) {
      const urlTemplate = ep.path.replace(":id", '${args.id}');
      handlerBody = `const res = await api.get(\`${urlTemplate}\`);`;
    } else if (isRead) {
      handlerBody = `let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("${ep.path}", { params: queryParams });`;
    } else if (ep.method === "PATCH") {
      handlerBody = `let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api({ method: "PATCH", url: "${ep.path}", data });`;
    } else {
      handlerBody = `let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("${ep.path}", data);`;
    }

    code += `
  server.tool(
    "${toolName}",
    "${desc.replace(/"/g, '\\"')}",
    ${schemaStr},
    ${annotations},
    async (args: any) => {
      try {
        ${handlerBody}
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: \`${toolName} error: \${error.message}\` }] };
      }
    }
  );
`;
  }

  code += `}\n`;

  fs.writeFileSync("src/auto-tools.ts", code);
  console.log(`✅ Generated src/auto-tools.ts with ${missing.length} tools`);
  console.log(`📝 Total tools: ${coveredPaths.size} (manual) + ${missing.length} (auto) = ${coveredPaths.size + missing.length}`);
}

function deriveToolName(path) {
  let cleaned = path
    .replace(/^\/api\/v1\//, "")
    .replace(/^\/bittensor\/v1\//, "bittensor_")
    .replace(/^\//, "")
    .replace(/:(\w+)/g, "by_$1")
    .replace(/[\/\-]/g, "_");
  return `spraay_${cleaned}`.replace(/__+/g, "_").replace(/_$/, "");
}

function deriveCategory(path) {
  const seg = path.replace(/^\/api\/v1\//, "").replace(/^\/bittensor\/v1\//, "bittensor/").split("/")[0];
  const map = {
    chat: "AI", models: "AI", batch: "Payments", swap: "DeFi",
    oracle: "Oracle", bridge: "Bridge", payroll: "Payroll",
    invoice: "Invoicing", analytics: "Analytics", escrow: "Escrow",
    inference: "AI Inference", notify: "Communication",
    webhook: "Webhooks", xmtp: "XMTP", rpc: "RPC",
    storage: "Storage", cron: "Scheduling", logs: "Logging",
    kyc: "KYC", auth: "Auth", audit: "Audit", tax: "Tax",
    gpu: "GPU/Compute", search: "Search/RAG",
    robots: "RTP (Robotics)", "agent-wallet": "Agent Wallets",
    prices: "DeFi", balances: "Data", resolve: "Identity",
    sctp: "Supply Chain", bittensor: "Bittensor", tokens: "Discovery",
  };
  return map[seg] || "General";
}

main().catch(err => { console.error("❌", err); process.exit(1); });
