// ⚡ AUTO-GENERATED by scripts/sync-tools.mjs — DO NOT EDIT
// Run "node scripts/sync-tools.mjs" to regenerate
// Generated: 2026-05-16T23:10:35.339Z

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

const ethAddr = z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Must be a valid Ethereum address");
const positiveAmount = z.string().regex(/^\d+(\.\d+)?$/, "Must be a positive number");

export const autoToolCount = 27;

export function registerAutoTools(server: McpServer, api: any) {

  server.tool(
    "spraay_tokens",
    "Tokens | [Discovery] | FREE",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/tokens", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_tokens error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_register",
    "Register Robot (RTP) | [RTP (Robotics)] | FREE",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/register", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_register error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_complete",
    "Report Task Complete (RTP) | [RTP (Robotics)] | FREE",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/complete", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_complete error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_update",
    "Update Robot (RTP) | [RTP (Robotics)] | FREE",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api({ method: "PATCH", url: "/api/v1/robots/update", data });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_update error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_deregister",
    "Remove Robot (RTP) | [RTP (Robotics)] | FREE",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/deregister", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_deregister error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_health",
    "Bittensor health | [Bittensor] | FREE",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/bittensor/v1/health", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_health error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_task",
    "Dispatch robot task (RTP) | [RTP (Robotics)] | $0.05 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/task", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_task error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_list",
    "Discover robots | [RTP (Robotics)] | $0.005 USDC",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/robots/list", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_list error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_status",
    "Poll task status | [RTP (Robotics)] | $0.002 USDC",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/robots/status", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_status error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_profile",
    "Robot profile | [RTP (Robotics)] | $0.002 USDC",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/robots/profile", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_profile error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_provision",
    "Provision agent wallet | [Agent Wallets] | $0.05 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/agent-wallet/provision", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_provision error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_session_key",
    "Add session key | [Agent Wallets] | $0.02 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/agent-wallet/session-key", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_session_key error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_info",
    "Agent wallet info | [Agent Wallets] | $0.005 USDC",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/agent-wallet/info", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_revoke_key",
    "Revoke session key | [Agent Wallets] | $0.02 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/agent-wallet/revoke-key", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_revoke_key error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_predict",
    "Predict wallet address | [Agent Wallets] | $0.001 USDC",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/agent-wallet/predict", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_predict error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_supplier",
    "Register supplier | [Supply Chain] | $0.02 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/supplier", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_supplier error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_supplier_by_id",
    "Get supplier | [Supply Chain] | $0.005 USDC",
    { id: z.string().min(1).describe("Resource ID") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/supplier/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_supplier_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_po",
    "Create purchase order | [Supply Chain] | $0.02 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/po", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_po error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_po_by_id",
    "Get purchase order | [Supply Chain] | $0.005 USDC",
    { id: z.string().min(1).describe("Resource ID") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/po/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_po_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice",
    "Submit invoice | [Supply Chain] | $0.02 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/invoice", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice_by_id",
    "Get invoice | [Supply Chain] | $0.005 USDC",
    { id: z.string().min(1).describe("Resource ID") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/invoice/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice_verify",
    "Verify invoice (AI) | [Supply Chain] | $0.03 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/invoice/verify", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice_verify error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_pay",
    "Execute supplier payment | [Supply Chain] | $0.10 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/pay", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_pay error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_models",
    "Bittensor models | [Bittensor] | $0.001 USDC",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/bittensor/v1/models", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_models error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_chat_completions",
    "Bittensor inference | [Bittensor] | $0.03 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/bittensor/v1/chat/completions", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_chat_completions error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_images_generations",
    "Bittensor image gen | [Bittensor] | $0.05 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/bittensor/v1/images/generations", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_images_generations error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_embeddings",
    "Bittensor embeddings | [Bittensor] | $0.005 USDC",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/bittensor/v1/embeddings", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_embeddings error: ${error.message}` }] };
      }
    }
  );
}
