// ⚡ AUTO-GENERATED by scripts/sync-tools.mjs — DO NOT EDIT
// Run "node scripts/sync-tools.mjs" to regenerate
// Generated: 2026-06-08T01:36:39.515Z

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

const ethAddr = z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Must be a valid Ethereum address");
const positiveAmount = z.string().regex(/^\d+(\.\d+)?$/, "Must be a positive number");

export const autoToolCount = 72;

export function registerAutoTools(server: McpServer, api: any) {

  server.tool(
    "spraay_tokens",
    "Tokens. Free to call. Read-only. Pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/tokens", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_tokens error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_register",
    "Register Robot (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let body = {};
        if (args.body) { try { body = JSON.parse(args.body); } catch { body = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/register", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_register error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_complete",
    "Report Task Complete (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let body = {};
        if (args.body) { try { body = JSON.parse(args.body); } catch { body = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/complete", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_complete error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_update",
    "Update Robot (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let body = {};
        if (args.body) { try { body = JSON.parse(args.body); } catch { body = { body: args.body }; } }
        const res = await api({ method: "PATCH", url: "/api/v1/robots/update", data: body });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_update error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_deregister",
    "Remove Robot (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let body = {};
        if (args.body) { try { body = JSON.parse(args.body); } catch { body = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/deregister", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_deregister error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_health",
    "Bittensor health. Free to call. Read-only. Pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/bittensor/v1/health", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_health error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_task",
    "Dispatch robot task (RTP). Costs $0.05 USDC per call. Provide the listed fields as typed arguments.",
    { "robot_id": z.string().describe("robot_id parameter"), "task": z.string().describe("task parameter"), "parameters": z.record(z.any()).optional().describe("parameters parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/robots/task", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_task error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_list",
    "Discover robots. Costs $0.005 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "capability": z.string().optional().describe("capability parameter"), "max_price": z.string().optional().describe("max_price parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/robots/list", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_list error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_status",
    "Poll task status. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "task_id": z.string().describe("task_id parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/robots/status", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_status error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_profile",
    "Robot profile. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "robot_id": z.string().describe("robot_id parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/robots/profile", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_profile error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_provision",
    "Provision agent wallet. Costs $0.05 USDC per call. Provide the listed fields as typed arguments.",
    { "agentId": z.string().describe("agentId parameter"), "agentType": z.string().optional().describe("agentType parameter"), "mode": z.string().optional().describe("mode parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/agent-wallet/provision", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_provision error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_session_key",
    "Add session key. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "walletAddress": z.string().describe("walletAddress parameter"), "sessionKeyAddress": z.string().describe("sessionKeyAddress parameter"), "spendLimitEth": z.string().describe("spendLimitEth parameter"), "durationHours": z.number().describe("durationHours parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/agent-wallet/session-key", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_session_key error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_info",
    "Agent wallet info. Costs $0.005 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "address": z.string().describe("address parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/agent-wallet/info", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_revoke_key",
    "Revoke session key. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "walletAddress": z.string().describe("walletAddress parameter"), "sessionKeyAddress": z.string().describe("sessionKeyAddress parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/agent-wallet/revoke-key", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_revoke_key error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_predict",
    "Predict wallet address. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "ownerAddress": z.string().describe("ownerAddress parameter"), "agentId": z.string().describe("agentId parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/agent-wallet/predict", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_predict error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_supplier",
    "Register supplier. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "name": z.string().describe("name parameter"), "wallet": z.string().describe("wallet parameter"), "paymentPrefs": z.record(z.any()).optional().describe("paymentPrefs parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/sctp/supplier", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_supplier error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_supplier_by_id",
    "Get supplier. Costs $0.005 USDC per call. Read-only. Provide the path parameter to fetch a single record.",
    { "id": z.string().min(1).describe("Path parameter that identifies the resource") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/supplier/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_supplier_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_po",
    "Create purchase order. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "supplierId": z.string().describe("supplierId parameter"), "lineItems": z.array(z.any()).describe("lineItems parameter"), "currency": z.string().optional().describe("currency parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/sctp/po", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_po error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_po_by_id",
    "Get purchase order. Costs $0.005 USDC per call. Read-only. Provide the path parameter to fetch a single record.",
    { "id": z.string().min(1).describe("Path parameter that identifies the resource") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/po/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_po_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice",
    "Submit invoice. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "poId": z.string().describe("poId parameter"), "supplierId": z.string().describe("supplierId parameter"), "amount": z.string().describe("amount parameter"), "currency": z.string().optional().describe("currency parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/sctp/invoice", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice_by_id",
    "Get invoice. Costs $0.005 USDC per call. Read-only. Provide the path parameter to fetch a single record.",
    { "id": z.string().min(1).describe("Path parameter that identifies the resource") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/invoice/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice_verify",
    "Verify invoice (AI). Costs $0.03 USDC per call. Provide the listed fields as typed arguments.",
    { "invoiceId": z.string().describe("invoiceId parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/sctp/invoice/verify", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice_verify error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_pay",
    "Execute supplier payment. Costs $0.10 USDC per call. Provide the listed fields as typed arguments.",
    { "invoiceId": z.string().describe("invoiceId parameter"), "batch": z.boolean().optional().describe("batch parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/sctp/pay", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_pay error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_models",
    "Bittensor models. Costs $0.001 USDC per call. Read-only. Pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/bittensor/v1/models", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_models error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_chat_completions",
    "Bittensor inference. Costs $0.03 USDC per call. Provide the listed fields as typed arguments.",
    { "model": z.string().describe("model parameter"), "messages": z.array(z.any()).describe("messages parameter"), "max_tokens": z.number().optional().describe("max_tokens parameter"), "temperature": z.number().optional().describe("temperature parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/bittensor/v1/chat/completions", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_chat_completions error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_images_generations",
    "Bittensor image gen. Costs $0.05 USDC per call. Provide the listed fields as typed arguments.",
    { "prompt": z.string().describe("prompt parameter"), "model": z.string().optional().describe("model parameter"), "n": z.number().optional().describe("n parameter"), "size": z.string().optional().describe("size parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/bittensor/v1/images/generations", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_images_generations error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_embeddings",
    "Bittensor embeddings. Costs $0.005 USDC per call. Provide the listed fields as typed arguments.",
    { "model": z.string().describe("model parameter"), "input": z.string().describe("input parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/bittensor/v1/embeddings", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_embeddings error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_jupiter_quote",
    "Jupiter swap quote. Costs $0.005 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "inputMint": z.string().describe("inputMint parameter"), "outputMint": z.string().describe("outputMint parameter"), "amount": z.string().describe("amount parameter"), "slippageBps": z.string().optional().describe("slippageBps parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/solana/jupiter/quote", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_jupiter_quote error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_jupiter_swap_tx",
    "Jupiter swap transaction. Costs $0.01 USDC per call. Provide the listed fields as typed arguments.",
    { "quoteResponse": z.record(z.any()).describe("quoteResponse parameter"), "userPublicKey": z.string().describe("userPublicKey parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/solana/jupiter/swap-tx", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_jupiter_swap_tx error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_helius_assets_by_owner",
    "Helius DAS assets. Costs $0.003 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "owner": z.string().describe("owner parameter"), "page": z.string().optional().describe("page parameter"), "limit": z.string().optional().describe("limit parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/solana/helius/assets-by-owner", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_helius_assets_by_owner error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_helius_asset",
    "Helius DAS single asset. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "id": z.string().describe("id parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/solana/helius/asset", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_helius_asset error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_pyth_price",
    "Pyth price feed. Costs $0.005 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "feedId": z.string().describe("feedId parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/solana/pyth/price", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_pyth_price error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_pyth_prices",
    "Pyth batch prices. Costs $0.008 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "feedIds": z.string().describe("feedIds parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/solana/pyth/prices", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_pyth_prices error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_portfolio_tokens",
    "Portfolio tokens. Costs $0.005 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "address": z.string().describe("address parameter"), "networks": z.string().optional().describe("networks parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/portfolio/tokens", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_portfolio_tokens error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_portfolio_nfts",
    "Portfolio NFTs. Costs $0.005 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "address": z.string().describe("address parameter"), "networks": z.string().optional().describe("networks parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/portfolio/nfts", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_portfolio_nfts error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_contract_read",
    "Read contract. Costs $0.002 USDC per call. Provide the listed fields as typed arguments.",
    { "chain": z.string().optional().describe("chain parameter"), "address": z.string().describe("address parameter"), "method": z.string().describe("method parameter"), "args": z.array(z.any()).optional().describe("args parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/contract/read", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_contract_read error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_contract_write",
    "Write contract. Costs $0.01 USDC per call. Provide the listed fields as typed arguments.",
    { "chain": z.string().optional().describe("chain parameter"), "address": z.string().describe("address parameter"), "method": z.string().describe("method parameter"), "args": z.array(z.any()).optional().describe("args parameter"), "walletId": z.string().optional().describe("walletId parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/contract/write", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_contract_write error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_defi_positions",
    "DeFi positions. Costs $0.008 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "address": z.string().describe("address parameter"), "chain": z.string().optional().describe("chain parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/defi/positions", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_defi_positions error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_xrp_batch",
    "XRP batch payments. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "senderSecret": z.string().describe("senderSecret parameter"), "recipients": z.array(z.any()).describe("recipients parameter"), "amounts": z.array(z.any()).describe("amounts parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/xrp/batch", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_xrp_batch error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_xrp_estimate",
    "XRP batch estimate. Costs $0.001 USDC per call. Provide the listed fields as typed arguments.",
    { "recipientCount": z.number().describe("recipientCount parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/xrp/estimate", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_xrp_estimate error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_xrp_info",
    "XRP Ledger info. Costs $0.001 USDC per call. Read-only. Pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/xrp/info", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_xrp_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_stellar_batch",
    "Stellar batch payments. Costs $0.02 USDC per call. Provide the listed fields as typed arguments.",
    { "sourceSecret": z.string().describe("sourceSecret parameter"), "recipients": z.array(z.any()).describe("recipients parameter"), "amounts": z.array(z.any()).describe("amounts parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/stellar/batch", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_stellar_batch error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_stellar_estimate",
    "Stellar batch estimate. Costs $0.001 USDC per call. Provide the listed fields as typed arguments.",
    { "recipientCount": z.number().describe("recipientCount parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/stellar/estimate", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_stellar_estimate error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_deposit",
    "Deposit USDC to open a prepaid compute credit account. Costs $0.01 USDC per call. Provide the listed fields as typed arguments.",
    { "depositor": z.string().describe("depositor parameter"), "amount": z.string().describe("amount parameter"), "expiresInDays": z.number().optional().describe("expiresInDays parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/compute-futures/deposit", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_deposit error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_balance",
    "Check remaining compute credit balance, tier, discount, and usage stats. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "id": z.string().describe("id parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/compute-futures/balance", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_balance error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_execute",
    "Run a compute job and deduct cost from the prepaid balance. Costs $0.001 USDC per call. Provide the listed fields as typed arguments.",
    { "futuresId": z.string().describe("futuresId parameter"), "type": z.string().describe("type parameter"), "model": z.string().optional().describe("model parameter"), "messages": z.array(z.any()).optional().describe("messages parameter"), "prompt": z.string().optional().describe("prompt parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/compute-futures/execute", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_execute error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_history",
    "Full usage ledger. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "id": z.string().describe("id parameter"), "limit": z.number().optional().describe("limit parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/compute-futures/history", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_history error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_refund",
    "Refund unused compute credit balance to the original depositor. Costs $0.01 USDC per call. Provide the listed fields as typed arguments.",
    { "futuresId": z.string().describe("futuresId parameter"), "caller": z.string().describe("caller parameter") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        const body = args;
        const res = await api.post("/api/v1/compute-futures/refund", body);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_refund error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_pricing",
    "Compute futures pricing. Costs $0.001 USDC per call. Read-only. Pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/compute-futures/pricing", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_pricing error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_dictionary_define",
    "Dictionary definition with phonetics and examples. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "word": z.string().describe("word parameter"), "lang": z.string().optional().describe("lang parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/dictionary/define", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_dictionary_define error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_dictionary_synonyms",
    "Synonyms and antonyms for a word. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "word": z.string().describe("word parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/dictionary/synonyms", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_dictionary_synonyms error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_dictionary_phonetics",
    "Phonetic transcription and audio URL. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "word": z.string().describe("word parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/dictionary/phonetics", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_dictionary_phonetics error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_search",
    "Search 250M+ academic papers (OpenAlex CC0). Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "q": z.string().describe("q parameter"), "filter": z.string().optional().describe("filter parameter"), "page": z.string().optional().describe("page parameter"), "per_page": z.string().optional().describe("per_page parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/papers/search", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_by_doi",
    "Paper metadata by DOI (OpenAlex). Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "doi": z.string().describe("doi parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/papers/by-doi", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_by_doi error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_by_author",
    "Papers by author name or ORCID (OpenAlex). Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "author": z.string().optional().describe("author parameter"), "orcid": z.string().optional().describe("orcid parameter"), "page": z.string().optional().describe("page parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/papers/by-author", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_by_author error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_citations",
    "Citation graph - cited-by count and references. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "doi": z.string().optional().describe("doi parameter"), "id": z.string().optional().describe("id parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/papers/citations", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_citations error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_trending",
    "Trending papers by topic in the last N days. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "topic": z.string().optional().describe("topic parameter"), "days": z.string().optional().describe("days parameter"), "per_page": z.string().optional().describe("per_page parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/papers/trending", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_trending error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_preprints_search",
    "Search arXiv preprints by keyword and category. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "q": z.string().optional().describe("q parameter"), "category": z.string().optional().describe("category parameter"), "max_results": z.string().optional().describe("max_results parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/preprints/search", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_preprints_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_preprints_by_id",
    "arXiv preprint metadata by ID. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "id": z.string().describe("id parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/preprints/by-id", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_preprints_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_preprints_recent",
    "Latest arXiv preprints by category. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "category": z.string().optional().describe("category parameter"), "max_results": z.string().optional().describe("max_results parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/preprints/recent", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_preprints_recent error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_by_doi",
    "Full Crossref metadata for any DOI. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "doi": z.string().describe("doi parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/scholarly/by-doi", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_by_doi error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_search",
    "Search 150M+ works via Crossref (CC0). Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "q": z.string().describe("q parameter"), "rows": z.string().optional().describe("rows parameter"), "offset": z.string().optional().describe("offset parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/scholarly/search", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_citations_count",
    "Citation count and references for a DOI. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "doi": z.string().describe("doi parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/scholarly/citations-count", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_citations_count error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_journal_info",
    "Journal metadata by ISSN. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "issn": z.string().describe("issn parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/scholarly/journal-info", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_journal_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_chemistry_compound",
    "PubChem compound by name, formula, or CID. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "name": z.string().optional().describe("name parameter"), "formula": z.string().optional().describe("formula parameter"), "cid": z.string().optional().describe("cid parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/chemistry/compound", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_chemistry_compound error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_chemistry_similarity",
    "Find structurally similar compounds in PubChem. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "cid": z.string().describe("cid parameter"), "threshold": z.string().optional().describe("threshold parameter"), "max_records": z.string().optional().describe("max_records parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/chemistry/similarity", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_chemistry_similarity error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_chemistry_bioactivity",
    "Biological assay results for a PubChem compound. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "cid": z.string().describe("cid parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/chemistry/bioactivity", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_chemistry_bioactivity error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_biomedical_search",
    "Search 36M+ biomedical papers in PubMed. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "q": z.string().describe("q parameter"), "max_results": z.string().optional().describe("max_results parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/biomedical/search", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_biomedical_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_biomedical_by_pmid",
    "Paper metadata by PubMed ID. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "pmid": z.string().describe("pmid parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/biomedical/by-pmid", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_biomedical_by_pmid error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_biomedical_related",
    "Related articles for a PubMed ID. Costs $0.002 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "pmid": z.string().describe("pmid parameter"), "max_results": z.string().optional().describe("max_results parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/biomedical/related", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_biomedical_related error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_demographics_census",
    "US Census data by state, county, or zip. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "dataset": z.string().optional().describe("dataset parameter"), "year": z.string().optional().describe("year parameter"), "variables": z.string().optional().describe("variables parameter"), "geo": z.string().optional().describe("geo parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/demographics/census", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_demographics_census error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_demographics_datasets",
    "Search Data.gov datasets by keyword. Costs $0.001 USDC per call. Read-only. Pass the listed fields directly as typed arguments.",
    { "q": z.string().describe("q parameter"), "rows": z.string().optional().describe("rows parameter") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get("/api/v1/research/demographics/datasets", { params: args });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_demographics_datasets error: ${error.message}` }] };
      }
    }
  );
}
