// ⚡ AUTO-GENERATED by scripts/sync-tools.mjs — DO NOT EDIT
// Run "node scripts/sync-tools.mjs" to regenerate
// Generated: 2026-06-07T18:57:26.502Z

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

const ethAddr = z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Must be a valid Ethereum address");
const positiveAmount = z.string().regex(/^\d+(\.\d+)?$/, "Must be a positive number");

export const autoToolCount = 84;

export function registerAutoTools(server: McpServer, api: any) {

  server.tool(
    "spraay_tokens",
    "Tokens. Free to call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/tokens", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_tokens error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_register",
    "Register Robot (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/register", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_register error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_complete",
    "Report Task Complete (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/complete", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_complete error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_update",
    "Update Robot (RTP). Free to call. Updates a resource; pass the fields to change as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api({ method: "PATCH", url: "/api/v1/robots/update", data });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_update error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_deregister",
    "Remove Robot (RTP). Free to call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/deregister", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_deregister error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_health",
    "Bittensor health. Free to call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/bittensor/v1/health", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_health error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_task",
    "Dispatch robot task (RTP). Costs $0.05 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/robots/task", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_task error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_list",
    "Discover robots. Costs $0.005 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/robots/list", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_list error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_status",
    "Poll task status. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/robots/status", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_status error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_robots_profile",
    "Robot profile. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/robots/profile", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_robots_profile error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_provision",
    "Provision agent wallet. Costs $0.05 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/agent-wallet/provision", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_provision error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_session_key",
    "Add session key. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/agent-wallet/session-key", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_session_key error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_info",
    "Agent wallet info. Costs $0.005 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/agent-wallet/info", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_revoke_key",
    "Revoke session key. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/agent-wallet/revoke-key", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_revoke_key error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_agent_wallet_predict",
    "Predict wallet address. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/agent-wallet/predict", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_agent_wallet_predict error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_supplier",
    "Register supplier. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/supplier", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_supplier error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_supplier_by_id",
    "Get supplier. Costs $0.005 USDC per call. Provide the required path parameter to fetch a single record.",
    { id: z.string().min(1).describe("Path parameter that identifies the resource") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/supplier/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_supplier_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_po",
    "Create purchase order. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/po", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_po error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_po_by_id",
    "Get purchase order. Costs $0.005 USDC per call. Provide the required path parameter to fetch a single record.",
    { id: z.string().min(1).describe("Path parameter that identifies the resource") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/po/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_po_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice",
    "Submit invoice. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/invoice", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice_by_id",
    "Get invoice. Costs $0.005 USDC per call. Provide the required path parameter to fetch a single record.",
    { id: z.string().min(1).describe("Path parameter that identifies the resource") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        const res = await api.get(`/api/v1/sctp/invoice/${args.id}`);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_invoice_verify",
    "Verify invoice (AI). Costs $0.03 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/invoice/verify", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_invoice_verify error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_sctp_pay",
    "Execute supplier payment. Costs $0.10 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/sctp/pay", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_sctp_pay error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_models",
    "Bittensor models. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/bittensor/v1/models", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_models error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_chat_completions",
    "Bittensor inference. Costs $0.03 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/bittensor/v1/chat/completions", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_chat_completions error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_images_generations",
    "Bittensor image gen. Costs $0.05 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/bittensor/v1/images/generations", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_images_generations error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_bittensor_embeddings",
    "Bittensor embeddings. Costs $0.005 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/bittensor/v1/embeddings", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_bittensor_embeddings error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_jupiter_quote",
    "Jupiter swap quote. Costs $0.005 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/solana/jupiter/quote", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_jupiter_quote error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_jupiter_swap_tx",
    "Jupiter swap transaction. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/solana/jupiter/swap-tx", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_jupiter_swap_tx error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_helius_assets_by_owner",
    "Helius DAS assets. Costs $0.003 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/solana/helius/assets-by-owner", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_helius_assets_by_owner error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_helius_asset",
    "Helius DAS single asset. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/solana/helius/asset", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_helius_asset error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_pyth_price",
    "Pyth price feed. Costs $0.005 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/solana/pyth/price", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_pyth_price error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_solana_pyth_prices",
    "Pyth batch prices. Costs $0.008 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/solana/pyth/prices", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_solana_pyth_prices error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_portfolio_tokens",
    "Portfolio tokens. Costs $0.005 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/portfolio/tokens", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_portfolio_tokens error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_portfolio_nfts",
    "Portfolio NFTs. Costs $0.005 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/portfolio/nfts", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_portfolio_nfts error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_contract_read",
    "Read contract. Costs $0.002 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/contract/read", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_contract_read error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_contract_write",
    "Write contract. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/contract/write", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_contract_write error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_defi_positions",
    "DeFi positions. Costs $0.008 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/defi/positions", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_defi_positions error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_xrp_batch",
    "XRP batch payments. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/xrp/batch", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_xrp_batch error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_xrp_estimate",
    "XRP batch estimate. Costs $0.001 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/xrp/estimate", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_xrp_estimate error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_xrp_info",
    "XRP Ledger info. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/xrp/info", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_xrp_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_stellar_batch",
    "Stellar batch payments. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/stellar/batch", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_stellar_batch error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_stellar_estimate",
    "Stellar batch estimate. Costs $0.001 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/stellar/estimate", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_stellar_estimate error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_deposit",
    "Deposit USDC to open a prepaid compute credit account. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/compute-futures/deposit", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_deposit error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_balance",
    "Check remaining compute credit balance, tier, discount, and usage stats. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/compute-futures/balance", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_balance error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_execute",
    "Run a compute job and deduct cost from the prepaid balance. Costs $0.001 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/compute-futures/execute", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_execute error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_history",
    "Full usage ledger. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/compute-futures/history", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_history error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_refund",
    "Refund unused compute credit balance to the original depositor. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/compute-futures/refund", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_refund error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_compute_futures_pricing",
    "Compute futures pricing. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/compute-futures/pricing", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_compute_futures_pricing error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_dictionary_define",
    "Dictionary definition with phonetics and examples. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/dictionary/define", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_dictionary_define error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_dictionary_synonyms",
    "Synonyms and antonyms for a word. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/dictionary/synonyms", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_dictionary_synonyms error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_dictionary_phonetics",
    "Phonetic transcription and audio URL. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/dictionary/phonetics", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_dictionary_phonetics error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_search",
    "Search 250M+ academic papers (OpenAlex CC0). Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/papers/search", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_by_doi",
    "Paper metadata by DOI (OpenAlex). Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/papers/by-doi", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_by_doi error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_by_author",
    "Papers by author name or ORCID (OpenAlex). Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/papers/by-author", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_by_author error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_citations",
    "Citation graph - cited-by count and references. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/papers/citations", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_citations error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_papers_trending",
    "Trending papers by topic in the last N days. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/papers/trending", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_papers_trending error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_preprints_search",
    "Search arXiv preprints by keyword and category. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/preprints/search", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_preprints_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_preprints_by_id",
    "arXiv preprint metadata by ID. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/preprints/by-id", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_preprints_by_id error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_preprints_recent",
    "Latest arXiv preprints by category. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/preprints/recent", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_preprints_recent error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_by_doi",
    "Full Crossref metadata for any DOI. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/scholarly/by-doi", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_by_doi error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_search",
    "Search 150M+ works via Crossref (CC0). Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/scholarly/search", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_citations_count",
    "Citation count and references for a DOI. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/scholarly/citations-count", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_citations_count error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_scholarly_journal_info",
    "Journal metadata by ISSN. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/scholarly/journal-info", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_scholarly_journal_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_chemistry_compound",
    "PubChem compound by name, formula, or CID. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/chemistry/compound", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_chemistry_compound error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_chemistry_similarity",
    "Find structurally similar compounds in PubChem. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/chemistry/similarity", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_chemistry_similarity error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_chemistry_bioactivity",
    "Biological assay results for a PubChem compound. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/chemistry/bioactivity", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_chemistry_bioactivity error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_biomedical_search",
    "Search 36M+ biomedical papers in PubMed. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/biomedical/search", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_biomedical_search error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_biomedical_by_pmid",
    "Paper metadata by PubMed ID. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/biomedical/by-pmid", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_biomedical_by_pmid error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_biomedical_related",
    "Related articles for a PubMed ID. Costs $0.002 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/biomedical/related", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_biomedical_related error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_demographics_census",
    "US Census data by state, county, or zip. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/demographics/census", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_demographics_census error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_research_demographics_datasets",
    "Search Data.gov datasets by keyword. Costs $0.001 USDC per call. Read-only; pass any query parameters as a JSON string via the params argument.",
    { params: z.string().optional().describe("Query parameters as JSON (e.g. {\"key\":\"value\"})") },
    { readOnlyHint: true, openWorldHint: true },
    async (args: any) => {
      try {
        let queryParams = {};
        if (args.params) { try { queryParams = JSON.parse(args.params); } catch {} }
        const res = await api.get("/api/v1/research/demographics/datasets", { params: queryParams });
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_research_demographics_datasets error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_geocode",
    "Geocode an address or place to lat/lng coordinates (OpenStreetMap). Costs $0.005 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/geocode", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_geocode error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_reverse_geocode",
    "Reverse geocode lat/lng to an address (OpenStreetMap). Costs $0.005 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/reverse-geocode", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_reverse_geocode error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_route",
    "Turn-by-turn directions between waypoints with distance and duration. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/route", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_route error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_isochrone",
    "Reachability polygon. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/isochrone", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_isochrone error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_elevation",
    "Terrain elevation at one or more coordinates (SRTM 30m). Costs $0.003 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/elevation", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_elevation error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_weather",
    "Current weather and 24h forecast at coordinates. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/weather", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_weather error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_weather_alerts",
    "Severe weather alerts at coordinates. Costs $0.01 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/weather-alerts", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_weather_alerts error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_flight_status",
    "Real-time flight status, times, gates, aircraft, delays (AeroDataBox). Costs $0.05 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/flight-status", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_flight_status error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_airport_info",
    "Airport details. Costs $0.03 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/airport-info", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_airport_info error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_distance_matrix",
    "Distance and duration matrix between multiple origin-destination pairs. Costs $0.02 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/distance-matrix", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_distance_matrix error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_nearby",
    "Find points of interest near coordinates. Costs $0.005 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/nearby", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_nearby error: ${error.message}` }] };
      }
    }
  );

  server.tool(
    "spraay_geo_timezone",
    "Country and timezone info at coordinates. Costs $0.003 USDC per call. Pass the request payload as a JSON string via the body argument.",
    { body: z.string().describe("JSON request body") },
    { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    async (args: any) => {
      try {
        let data = {};
        if (args.body) { try { data = JSON.parse(args.body); } catch { data = { body: args.body }; } }
        const res = await api.post("/api/v1/geo/timezone", data);
        return { content: [{ type: "text" as const, text: JSON.stringify(res.data, null, 2) }] };
      } catch (error: any) {
        return { isError: true, content: [{ type: "text" as const, text: `spraay_geo_timezone error: ${error.message}` }] };
      }
    }
  );
}
